name:                craffiti
version:             0.1.0.0
github:              "ynishi/craffiti"
license:             BSD3
author:              "Yutaka Nishimura"
maintainer:          "ytk.nishimura@gmail.com"
copyright:           "2021 Yutaka Nishimura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/craffiti#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- foldl
- optparse-applicative
- rio
- text
- turtle
- utf8-string
- operational
- yaml
- raw-strings-qq
- directory
- filepath
- containers
- split

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

library:
  source-dirs: src

executables:
  craffiti-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - craffiti

tests:
  craffiti-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - craffiti
